spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_OAUTH2_CLIENT_ID}
            client-secret: ${FACEBOOK_OAUTH2_CLIENT_SECRET}
          okta:
            client-id: ${OKTA_OAUTH2_CLIENT_ID}
            client-secret: ${OKTA_OAUTH2_CLIENT_SECRET}
        provider:
          okta:
            authorization-uri: ${OKTA_OAUTH2_DOMAIN}.auth0.com/authorize
            token-uri: ${OKTA_OAUTH2_DOMAIN}.auth0.com/oauth/token
            jwk-set-uri: ${OKTA_OAUTH2_DOMAIN}.auth0.com/.well-known/jwks.json

management:
  endpoint:
    web:
      exposure:
        include: health,info
    info:
      enabled: true
    health:
      roles: ACTUATOR
      show-components: always
      show-details: always

debug: true
logging:
  level:
    org:
      springframework:
        security: TRACE
